version: "3.3"
services:
  nodejs:
    build: 
      context: .
    image: ahmetbcakici/trendyol-case
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=ahmethost
      - MYSQL_USER=ahmet
      - MYSQL_PASS=123
      - MYSQL_DB=Shorter
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8080:8080"
    container_name: ahmet-nodejs-app
  mysql:
    image: mysql:5.7
    ports:
      - 8083:3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ahmet
      - MYSQL_PASSWORD=123 
      - MYSQL_DATABASE=Shorter
    container_name: ahmet-mysql-app
networks:
  frontend:
  backend: